

<?php $__env->startSection('title', 'Search Result - Laravel Demo Application'); ?>

<?php $__env->startSection('content'); ?>
    <div class="container">
        <div class="container position-relative">
            <div class=" p-4 position-relative z-3 ">
                <!-- Main Title -->
                <div class="fw-bold text-dark fs-3 fs-md-2 fs-lg-1 mb-4 text-center">
                    Bạn muốn thuê xe ở đâu
                </div>

                <!-- Search Form -->
                <div class="d-flex flex-column flex-lg-row gap-3 align-items-stretch">
                    <!-- Left Section: Input Fields -->
                    <div class="d-flex flex-column flex-lg-row flex-grow-1 gap-3">
                        <!-- Location Input -->
                        <div class="flex-grow-1">
                            <div style="height:52px"
                                class="input-group border rounded position-relative d-flex align-items-center">
                                <input type="text" class="form-control border-0" id="locationInput" placeholder="Địa điểm"
                                    readonly>
                                <!-- Select from Map Button -->
                                <button class="btn-select-map btn bg-white px-3 py-2 rounded-3"
                                    onclick="toggleLocationDropdown()">
                                    Chọn từ bản đồ
                                </button>
                            </div>
                        </div>

                        <!-- Date Input -->
                        <div class="flex-grow-1">
                            <div style="height:52px" class="input-group border rounded position-relative">

                                <div class="d-flex align-items-center px-3" style="margin-right: auto">
                                    <div id="timeButtonText">Thời gian</div>
                                </div>
                                <button class="btn-select-map btn bg-white px-3 py-2 rounded-3" onclick="toggleCalendar()"
                                    id="timeButton">
                                    Chọn ngày
                                </button>
                                <input type="date" class="form-control border-0" id="dateInput" style="display: none;">

                                <!-- Custom Calendar Picker -->
                                <div id="calendarPicker"
                                    class="position-absolute shadow-lg bg-white border rounded-3 shadow-lg p-3"
                                    style="top: 100%; left: 0; z-index: 1000; min-width: 280px; display: none;">
                                    <!-- Calendar Header -->
                                    <div class="d-flex justify-content-between align-items-center mb-3">
                                        <div class="d-flex align-items-center gap-2">
                                            <span class="fw-bold" id="currentMonth">August 2025</span>
                                            <i class="bi bi-chevron-down text-muted"></i>
                                        </div>
                                        <div class="d-flex gap-1">
                                            <button class="btn btn-sm btn-light" onclick="previousMonth()">↑</button>
                                            <button class="btn btn-sm btn-light" onclick="nextMonth()">↓</button>
                                        </div>
                                    </div>

                                    <!-- Week Days -->
                                    <div class="d-flex mb-2">
                                        <div class="flex-fill text-center text-muted small fw-medium">Su</div>
                                        <div class="flex-fill text-center text-muted small fw-medium">Mo</div>
                                        <div class="flex-fill text-center text-muted small fw-medium">Tu</div>
                                        <div class="flex-fill text-center text-muted small fw-medium">We</div>
                                        <div class="flex-fill text-center text-muted small fw-medium">Th</div>
                                        <div class="flex-fill text-center text-muted small fw-medium">Fr</div>
                                        <div class="flex-fill text-center text-muted small fw-medium">Sa</div>
                                    </div>

                                    <!-- Calendar Grid -->
                                    <div id="calendarGrid" class="mb-3">
                                        <!-- Calendar days will be generated by JavaScript -->
                                    </div>

                                    <!-- Calendar Footer -->
                                    <div class="d-flex justify-content-between">
                                        <button class="btn btn-sm btn-outline-secondary"
                                            onclick="clearDate()">Clear</button>
                                        <button class="btn btn-sm btn-outline-primary" onclick="setToday()">Today</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Hour Input -->
                        <div class="flex-grow-1">
                            <div style="height:52px" class="input-group border rounded position-relative">
                                <div class="d-flex align-items-center px-3" style="margin-right: auto">
                                    <span id="pickupReturnText" class="text-end">Nhận trả xe</span>
                                </div>
                                <button class="btn-select-map btn bg-white px-3 py-2 rounded-3" onclick="toggleTimePicker()"
                                    id="pickupReturnButton">
                                    Chọn giờ
                                </button>
                                <input type="time" class="form-control border-0" id="timeInput" style="display: none;">

                                <!-- Time Picker Dropdown -->
                                <div id="timePicker"
                                    class="position-absolute bg-white border shadow-lg rounded-3 shadow-lg p-3"
                                    style="top: 100%; left: 0; z-index: 1000; min-width: 250px; display: none;">
                                    <!-- Pick-up Time -->
                                    <div class="mb-3">
                                        <label class="form-label fw-medium text-dark mb-2">Giờ nhận</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control border rounded-3" id="pickupTime"
                                                placeholder="10 AM" readonly>
                                            <button class="btn btn-outline-secondary border-start-0"
                                                onclick="toggleTimeDropdown('pickup')" type="button">
                                                <i class="bi bi-chevron-down"></i>
                                            </button>
                                        </div>
                                    </div>

                                    <!-- Return Time -->
                                    <div class="mb-3">
                                        <label class="form-label fw-medium text-dark mb-2">Giờ trả</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control border rounded-3" id="returnTime"
                                                placeholder="10 AM" readonly>
                                            <button class="btn btn-outline-secondary border-start-0"
                                                onclick="toggleTimeDropdown('return')" type="button">
                                                <i class="bi bi-chevron-down"></i>
                                            </button>
                                        </div>
                                    </div>

                                    <!-- Time Options Dropdowns -->
                                    <div id="pickupTimeOptions"
                                        class="position-absolute bg-white border rounded-3 shadow-lg"
                                        style="top: 0; left: 100%; z-index: 1001; min-width: 120px; max-height: 200px; overflow-y: auto; display: none;">
                                        <!-- Time options will be generated by JavaScript -->
                                    </div>

                                    <div id="returnTimeOptions"
                                        class="position-absolute bg-white border rounded-3 shadow-lg"
                                        style="top: 0; left: 100%; z-index: 1001; min-width: 120px; max-height: 200px; overflow-y: auto; display: none;">
                                        <!-- Time options will be generated by JavaScript -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Right Section: Search Button -->
                    <div class="d-flex align-items-end">
                        <button class="btn btn-primary fw-bold px-5 py-3 rounded-4 w-100" style="min-width: 150px"
                            onclick="toggleFilterDrawer()">
                            Tìm xe
                        </button>
                    </div>
                </div>
            </div>

            <!-- Location Dropdown/Overlay -->
            <div id="locationDropdown" class="bg-white rounded-4 shadow-lg p-4 mt-3 position-relative z-3"
                style="max-width: 400px; display: none;">
                <!-- Current Location -->
                <div class="mb-3">
                    <div class="d-flex align-items-center gap-2 mb-2">
                        <i class="bi bi-geo-alt-fill text-primary"></i>
                        <span class="fw-medium text-dark">Vị trí hiện tại</span>
                    </div>
                    <div class="text-muted small cursor-pointer hover-bg-light p-2 rounded-3"
                        onclick="selectLocation('Quận 1, TP Hồ Chí Minh')">Quận 1, TP Hồ Chí Minh</div>
                </div>

                <!-- Suggested Destinations -->
                <div>
                    <div class="fw-medium text-dark mb-2">Điểm đến được đề xuất</div>
                    <div class="space-y-2">
                        <!-- Suggested Location 1 -->
                        <div class="d-flex align-items-center gap-3 p-2 rounded-3 hover-bg-light cursor-pointer"
                            onclick="selectLocation('Quận 1, 72 Lê Thánh Tôn Bến Nghé, Quận 1, Hồ Chí Minh')">
                            <i class="bi bi-geo-alt-fill text-primary"></i>
                            <div class="text-muted small">Quận 1, 72 Lê Thánh Tôn Bến Nghé, Quận 1, Hồ Chí Minh</div>
                        </div>

                        <!-- Suggested Location 2 -->
                        <div class="d-flex align-items-center gap-3 p-2 rounded-3 hover-bg-light cursor-pointer"
                            onclick="selectLocation('Quận 3, 123 Nguyễn Thị Minh Khai, Phường 6, Quận 3, Hồ Chí Minh')">
                            <i class="bi bi-geo-alt-fill text-primary"></i>
                            <div class="text-muted small">Quận 3, 123 Nguyễn Thị Minh Khai, Phường 6, Quận 3, Hồ Chí Minh
                            </div>
                        </div>

                        <!-- Suggested Location 3 -->
                        <div class="d-flex align-items-center gap-3 p-2 rounded-3 hover-bg-light cursor-pointer"
                            onclick="selectLocation('Quận 7, 456 Nguyễn Thị Thập, Phường Tân Phú, Quận 7, Hồ Chí Minh')">
                            <i class="bi bi-geo-alt-fill text-primary"></i>
                            <div class="text-muted small">Quận 7, 456 Nguyễn Thị Thập, Phường Tân Phú, Quận 7, Hồ Chí Minh
                            </div>
                        </div>

                        <!-- Suggested Location 4 -->
                        <div class="d-flex align-items-center gap-3 p-2 rounded-3 hover-bg-light cursor-pointer"
                            onclick="selectLocation('Quận 2, 789 Mai Chí Thọ, Phường An Phú, Quận 2, Hồ Chí Minh')">
                            <i class="bi bi-geo-alt-fill text-primary"></i>
                            <div class="text-muted small">Quận 2, 789 Mai Chí Thọ, Phường An Phú, Quận 2, Hồ Chí Minh</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Products Search -->
        <div class="container">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <span class="fw-bold mb-0 fs-3 fs-md-2 fs-lg-1">Hơn 10 xe Kia Rio 2015 có sẵn</span>
            </div>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
                <div>
                    <?php echo $__env->make('components.product-recomend', [
                        'name' => 'Kia Rio 2015',
                        'rating' => '4.0',
                        'location' => 'Quận 1, TP Hồ Chí Minh',
                        'image' => asset('assets/images/product-rcm.png'),
                        'old_price' => '976.000đ',
                        'price' => '856.000đ',
                    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
                </div>
            </div>
        </div>
    <?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH E:\otod\resources\views/search-result.blade.php ENDPATH**/ ?>